name = "Vital"
author = "usevital, SkywardMC"
version = "3.0.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9da71bde5e9ea2e1ddc2f25384886b5cd7374aed42460ef432b682ff1bfebc86"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
