name = "Vital"
author = "usevital, SkywardMC"
version = "3.0.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7eec7959d380a2054f7e697f2ba8569cd1817a632a4da28dad1b0821ad71119d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
