name = "Vital"
author = "usevital, SkywardMC"
version = "2.2.2+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56e88183aa7b407f8f809928e5ec3f62042c8b96c246d3e19e5a2d630e77e8d2"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
